spring:
  application:
    name: seat-inventory

  datasource:
    url: jdbc:postgresql://localhost:5433/seat_inventory_DB
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-event-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

  mongodb:
    host: localhost
    port: 27017
    database: seat_inventory_service

server:
  port: 8082
